Logging to /home/paulgilles/Bachelorarbeit/modified-improved-diffusion-main/Models/2023-07-12_15-46-16/sample_2023-07-13_08-02-25
creating model and diffusion...
Traceback (most recent call last):
  File "scripts/sampling.py", line 184, in <module>
    main()
  File "scripts/sampling.py", line 54, in main
    dist_util.load_state_dict(args.model_path, map_location="cpu")
  File "/home/paulgilles/Bachelorarbeit/modified-improved-diffusion-main/modified_improved_diffusion/dist_util.py", line 58, in load_state_dict
    with bf.BlobFile(path, "rb") as f:
  File "/home/paulgilles/.local/lib/python3.8/site-packages/blobfile/_ops.py", line 366, in BlobFile
    return default_context.BlobFile(
  File "/home/paulgilles/.local/lib/python3.8/site-packages/blobfile/_context.py", line 921, in BlobFile
    f = io.FileIO(path, mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: 'Models/2023-07-12_15-46-16/ema_0.9999_200000.pt'
